name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, allowing access
      - name: Checkout code
        uses: actions/checkout@v4

   # This action sets up the JFrog CLI with the Artifactory URL and access token     
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          jfrog_version: latest
        env:
          JF_URL: ${{ secrets.JF_URL }}  # Replace vars with secrets for security
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          
      - name: Configure JFrog CLI
        run: |
          export SERVER_ID= "test"
          jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false

      # Set up Java JDK (change '11' if necessary)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify Maven installation
        run: |
          mvn --version

      - name: Configure Maven with JFrog
        run: |
          jf mvn-config \
            --repo-resolve-releases demo-libs-release \
            --repo-resolve-snapshots demo-libs-snapshot \
            --repo-deploy-releases demo-libs-release \
            --repo-deploy-snapshots demo-libs-snapshot
      # Use JFrog Maven Install
      - name: Run JFrog Maven Install
        run: jf mvn install
