name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, allowing access
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java JDK (change '11' if necessary)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Configure Maven with Artifactory authentication
      - name: Configure Maven settings
        run: |
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">
            <servers>
              <server>
                <id>demo-libs-release</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
              </server>
              <server>
                <id>demo-libs-snapshot</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>artifactory</id>
                <repositories>
                  <repository>
                    <id>demo-libs-release</id> <!-- URL for releases -->
                    <url>https://incloudmaster.jfrog.io/artifactory/demo-libs-release</url> <!-- Set your Artifactory URL here -->
                    <snapshots>
                      <enabled>false</enabled>
                    </snapshots>
                  </repository>
                  <repository>
                    <id>demo-libs-snapshot</id> <!-- URL for snapshots -->
                    <url>https://incloudmaster.jfrog.io/artifactory/demo-libs-snapshot</url> <!-- Set your Artifactory URL here -->
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>artifactory</activeProfile>
            </activeProfiles>
          </settings>" > $HOME/.m2/settings.xml

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean install --settings $HOME/.m2/settings.xml
